version: "3.8"
services:
  geth-second:
    container_name: geth-second
    image: ethereum/client-go:latest
    restart: always
    working_dir: /poa
    hostname: geth-second
    volumes:
      - $PWD/geth-second:/poa
      - ./config:/config
    ports:
      - 30457:30456
      - 8552:8551
      - 8547:8545
      - 8548:8546
    command: |
      --networkid 1112
      --syncmode "full"
      --datadir "datadir"
      --port 30456
      --bootnodes "enode://eeee24c0290e703c04d12dbe6c424decfde2b7aca313b541b02bf8b7a365f3ccc867d0ae9708341cb04f2f06486c0e56f6e3a41584d225ec0b10aace45bfe0b6@validator1:30456"
      --authrpc.vhosts *
      --authrpc.addr 0.0.0.0
      --authrpc.jwtsecret=/config/jwtsecret
      --http
      --http.api=eth,net,web3,txpool,debug,admin
      --http.addr=0.0.0.0
      --http.corsdomain=*
      --http.vhosts=*
      --ws
      --ws.api=eth,net,web3,txpool,debug
      --ws.addr=0.0.0.0
      --ws.origins=*
    networks:
      - poa-migrate-network

  lighthouse-beacon-second:
    image: sigp/lighthouse
    volumes:
      - ./consensus/lighthouse-beacon-second:/root/.lighthouse
      - ./config:/config
    ports:
      - 9102:9100
      - 5003:5002
    command:
      - lighthouse
      - beacon
      - --execution-endpoint=http://validator1:8551
      - --execution-jwt=/config/jwtsecret
      - --disable-peer-scoring
      - --disable-packet-filter
      - --http-allow-sync-stalled
      - --http
      - --http-address=0.0.0.0
      - --http-port=5002
      - --http-allow-origin=*
      - --gui
      - --eth1
      - --target-peers=2
      - --enr-address=lighthouse-beacon-second
      - --enr-udp-port=9100
      - --enr-tcp-port=9100
      - --port=9100
      - --testnet-dir=/config
      - --checkpoint-sync-url=http://lighthouse-beacon:5002
      - --debug-level=debug
      - --boot-nodes=enr:-MS4QON0VhBb024MAx9V9Ry92FYREqWmeNjX7It8X3jPYJnUA3IlPtwq96gqAIbAa4P9Dg48RkmaDKOraRUk6_ECye5Ah2F0dG5ldHOIAAAAAACAAQCEZXRoMpAMws24UAAAAP__________gmlkgnY0gmlwhAAAAACEcXVpY4IjjYlzZWNwMjU2azGhAj26gBe08QusoPR9jvONClnT5BKvKhh6wfEIQkdFvJw4iHN5bmNuZXRzD4N0Y3CCI4yDdWRwgiOM
    networks:
      - poa-migrate-network

  lighthouse-validator-second:
    image: sigp/lighthouse
    volumes:
      - ./consensus/validatordata-lighthouse-second:/root/.lighthouse
      - ./config:/config
    ports:
      - 5064:5062
    command:
      - lighthouse
      - vc
      - --beacon-nodes=http://lighthouse-beacon-second:5002
      - --testnet-dir=/config
      - --init-slashing-protection
      - --graffiti=lighthouse-vc
      - --suggested-fee-recipient=0x943CAAa62c32655F5B35E22106A5438a78F42e61
      - --debug-level=info
      - --http
      - --http-address=0.0.0.0
      - --http-port=5062
      - --http-allow-origin=*
      - --unencrypted-http-transport
    networks:
      - poa-migrate-network
    depends_on:
      lighthouse-beacon-second:
        condition: service_started

networks:
  poa-migrate-network:
    name: poa_migrate_network
    external: true
