CONFIG_NAME: foundation
PRESET_BASE: mainnet

# Genesis
# ---------------------------------------------------------------
# `2**14` (= 16,384)
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 1
# Friday, April 22, 2022 9:00:00 AM +UTC
MIN_GENESIS_TIME: 1706850882
GENESIS_FORK_VERSION: 0x10001234
GENESIS_DELAY: 0

# Altair
ALTAIR_FORK_EPOCH: 1
ALTAIR_FORK_VERSION: 0x20001234

# Merge
BELLATRIX_FORK_EPOCH: 2
BELLATRIX_FORK_VERSION: 0x30001234
TERMINAL_TOTAL_DIFFICULTY: 300
TERMINAL_BLOCK_HASH: 0x0000000000000000000000000000000000000000000000000000000000000000
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 18446744073709551615

# Capella
CAPELLA_FORK_EPOCH: 3
CAPELLA_FORK_VERSION: 0x40001234

# Deneb
DENEB_FORK_EPOCH: 10000000
DENEB_FORK_VERSION: 0x50001234

# EIP4844
# EIP4844_FORK_EPOCH: 5
# EIP4844_FORK_VERSION: 0x20000093

# MAX_WITHDRAWALS_PER_PAYLOAD: 16

# Time parameters
# ---------------------------------------------------------------
# 12 seconds
SECONDS_PER_SLOT: 3
# 14 (estimate from Eth1 mainnet)
SECONDS_PER_ETH1_BLOCK: 3
# 2**8 (= 256) epochs ~27 hours
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256
# 2**8 (= 256) epochs ~27 hours
SHARD_COMMITTEE_PERIOD: 256
# 2**11 (= 2,048) Eth1 blocks ~8 hours
ETH1_FOLLOW_DISTANCE: 2048
EPOCHS_PER_ETH1_VOTING_PERIOD: 100

SLOTS_PER_EPOCH: 6

# Validator cycle
# ---------------------------------------------------------------
# 2**2 (= 4)
INACTIVITY_SCORE_BIAS: 4
# 2**4 (= 16)
INACTIVITY_SCORE_RECOVERY_RATE: 16
# 2**4 * 10**9 (= 16,000,000,000) Gwei
EJECTION_BALANCE: 16000000000
# 2**2 (= 4)
MIN_PER_EPOCH_CHURN_LIMIT: 4
# 2**16 (= 65,536)
CHURN_LIMIT_QUOTIENT: 65536

# [New in Deneb:EIP7514] 2**3 (= 8)
MAX_PER_EPOCH_ACTIVATION_CHURN_LIMIT: 8

# Fork choice
# ---------------------------------------------------------------
# 40%
PROPOSER_SCORE_BOOST: 40

# Deposit contract
DEPOSIT_CHAIN_ID: 1112
DEPOSIT_NETWORK_ID: 1112
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242

# Networking

# ---------------------------------------------------------------

# `10 * 2**20` (= 10485760, 10 MiB)

GOSSIP_MAX_SIZE: 10485760

# `2**10` (= 1024)

MAX_REQUEST_BLOCKS: 1024

# `2**8` (= 256)

EPOCHS_PER_SUBNET_SUBSCRIPTION: 256

# `MIN_VALIDATOR_WITHDRAWABILITY_DELAY + CHURN_LIMIT_QUOTIENT // 2` (= 33024, ~5 months)

MIN_EPOCHS_FOR_BLOCK_REQUESTS: 33024

# `10 * 2**20` (=10485760, 10 MiB)

MAX_CHUNK_SIZE: 10485760

# 5s

TTFB_TIMEOUT: 5

# 10s

RESP_TIMEOUT: 10

ATTESTATION_PROPAGATION_SLOT_RANGE: 32

# 500ms

MAXIMUM_GOSSIP_CLOCK_DISPARITY: 500

MESSAGE_DOMAIN_INVALID_SNAPPY: 0x00000000

MESSAGE_DOMAIN_VALID_SNAPPY: 0x01000000

# 2 subnets per node

SUBNETS_PER_NODE: 2

# 2**8 (= 64)

ATTESTATION_SUBNET_COUNT: 64

ATTESTATION_SUBNET_EXTRA_BITS: 0

# ceillog2(ATTESTATION_SUBNET_COUNT) + ATTESTATION_SUBNET_EXTRA_BITS

ATTESTATION_SUBNET_PREFIX_BITS: 6

# Deneb

# `2**7` (=128)

MAX_REQUEST_BLOCKS_DENEB: 128

# MAX_REQUEST_BLOCKS_DENEB * MAX_BLOBS_PER_BLOCK

MAX_REQUEST_BLOB_SIDECARS: 768

# `2**12` (= 4096 epochs, ~18 days)

MIN_EPOCHS_FOR_BLOB_SIDECARS_REQUESTS: 4096

# `6`

BLOB_SIDECAR_SUBNET_COUNT: 6

# `uint64(6)`

MAX_BLOBS_PER_BLOCK: 6
